name: clang-tidy Review
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ZedThree/clang-tidy-review@v0.8.2
      id: review 
      with:
        cmake_command: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=on
        apt_packages: libopenmpi-dev
        build_dir: build
  
